#! /bin/sh

sxhkd &

# $HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
# compton --inactive-dim 0.2 --no-fading-openclose --inactive-dim-fixed --config /dev/null &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d term web chat code steam VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' state=monocle
bspc rule -a TelegramDesktop desktop='^3' state=monocle
bspc rule -a Steam desktop='^5'
bspc rule -a Zathura state=tiled
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
